[package]
name = "profiling-template"
version = "0.0.0"
edition = "2021"

[package.metadata.component]
package = "psh:profiling"

[package.metadata.component.target.dependencies]

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
profiling = { path = "../.." }