[package]
name = "strategy"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "strategy-macros",
    "strategy-prelude",
    "strategy-runtime",
]
exclude = [
    "strategy-compiler",
    "strategy-template",
    "test-resources",
]

[features]
strategy-dev = ["strategy-macros", "strategy-prelude"]
strategy-macros = []
strategy-prelude = []

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
strategy-macros = { path = "./strategy-macros" }
strategy-prelude = { path = "./strategy-prelude" }
