[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
]
exclude = [
    "docs",
]

[features]

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
