[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "docs/template",
    "crates/op/*"
]
exclude = [
]

[workspace.package]
version = "0.1.0"

[features]

[dependencies]
wit-bindgen = "0.22.0"