[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "docs/template",
]
exclude = [
]

[workspace.package]
version = "0.1.0"

[features]

[dependencies]
bitflags = "2.5.0"
wit-bindgen = "0.22.0"
