[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "macros",
    "runtime",
    "prelude",
    "prelude/include/*",
]
exclude = [
    "aot",
    "docs",
    "test-resources",
]

[features]
profiling-dev = ["profiling-macros", "profiling-prelude"]
profiling-macros = []
profiling-prelude = []

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
profiling-macros = { path =  "./macros" }
profiling-prelude = { path = "./prelude" }
