[package]
name = "profiling-runtime"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
wasmtime = "16.0.0"
perf-event-rs = { path = "../../perf-event-rs" }
profiling-prelude-perf-types = { path = "../prelude/include/perf/types" }
