[package]
name = "profiling-test-exit"
version = "0.0.0"
edition = "2021"

[lib]
name = "profiling"
crate-type = ["cdylib"]
path = "src/main.rs"

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
profiling = { path = "../../..", features = ["prelude"] }
