[package]
name = "profiling-op-perf"
version = "0.0.0"
edition = "2021"

[dependencies]
wasmtime = "18.0.1"
anyhow = "1.0.80"
wasmtime-wasi = "18.0.1"
perf-event-rs = { path = "../../../perf-event-rs" }
