[package]
name = "profiling-prelude-perf"
version = "0.0.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.16.0"
profiling-prelude-intrinsics = { path = "../intrinsics" }
profiling-prelude-perf-types = { path = "types" }

[build-dependencies]
wit-bindgen = "0.16.0"
