[package]
name = "profiling-prelude-perf-types"
version = "0.0.0"
edition = "2021"

[dependencies]
rkyv = { version = "0.7.43", default-features = false, features = ["alloc", "size_32", "validation"] }
