[package]
name = "profiling-op-file"
version = "0.0.0"
edition = "2021"

[dependencies]
wasmtime = "16.0.0"
profiling-runtime = { path = "../../runtime" }
profiling-op-intrinsics = { path = "../intrinsics" }
