[package]
name = "strategy-test-panic"
version = "0.0.0"
edition = "2021"

[lib]
name = "strategy"
crate-type = ["cdylib"]

#[profile.release]
#lto = true
#strip = true
#codegen-units = 1

[dependencies]
strategy = { path = "../../..", features = ["strategy-dev"] }
